global using CommunityToolkit.Mvvm.ComponentModel;
global using CommunityToolkit.Mvvm.Input;
global using Microsoft.Extensions.Logging;
global using PokemonBattleJournal.Models;
global using PokemonBattleJournal.Resources.Fonts;
global using PokemonBattleJournal.Services;
global using PokemonBattleJournal.Utilities;
global using PokemonBattleJournal.ViewModels;
global using PokemonBattleJournal.Views;
